### ISSUE TITLE
Strongbox Item Model + Sound are bugged

### ISSUE THREAD

**Issue by BlueIsADude** [Solstice-MC/Rolling-Stones#4]
The Strongbox's item model is bugged, showing the entire texture on each side.

<img width="651" height="601" alt="Image" src="https://github.com/user-attachments/assets/584c1d31-e6de-4988-a79a-0081b808aa14" />

<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/02ed5d3d-6f4b-48b6-9006-77532e572aec" />

Additionally, the block's closing sound effect goes on for a bit longer than it should.

**Comment by Soumeh** [comment]
could you attach your modlist? i've never seen the inventory model bug out like that

**Comment by BlueIsADude** [comment]
Sure thing! I also thought it was another mod at first, but i made a new instance with nothing but rolling stones and mod menu (+ their dependencies)

<img width="1535" height="401" alt="Image" src="https://github.com/user-attachments/assets/98a35e35-587a-4b37-b466-0f6b6ea6187e" />

**Comment by Soumeh** [comment]
should be fixed in 0.3.0, thanks for the report!
i gave the strongbox a dedicated item renderer which should hopefully fix it
closing sound effect should be fixed too
btw you can feel free to report any issues on the discord instead if you don't want to make new github issues all the time
invite link's on the modrinth page

**Comment by BlueIsADude** [comment]
I updated to 0.3.0, yet for some reason the strongbox item model is still bugged
I even made another completely fresh instance with just rolling stones installed, just in case, and yet the issue is still there.

<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/17e3d374-65aa-4816-9090-e6bab3b6df43" />

<img width="1536" height="237" alt="Image" src="https://github.com/user-attachments/assets/a1aa81be-3864-441c-8ce7-80b3af1452dc" />
